name: flokk-contacts
version: 0.9.0
summary: Flokk Contacts
description: Manage Contacts
confinement: strict
base: core18
grade: devel
parts:
  snaptest:
    plugin: dump
    source: ./dist.tar.gz

apps:
  flokk-contacts:
    command: flokk_contacts
    extensions: [gnome-3-28]
    plugs:
      - x11
      - opengl
      - network
      - home
    common-id: flokk-contacts
    environment:
      __EGL_VENDOR_LIBRARY_DIRS: $__EGL_VENDOR_LIBRARY_DIRS:$SNAP/gnome-platform/usr/share/glvnd/egl_vendor.d
